"""empty message

Revision ID: 2711c44be2b2
Revises: f8daafaad9b8
Create Date: 2017-12-29 15:51:38.805070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2711c44be2b2'
down_revision = 'f8daafaad9b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
