"""empty message

Revision ID: 5a0eba444019
Revises: bfdff98de29d
Create Date: 2017-12-25 12:23:06.288722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0eba444019'
down_revision = 'bfdff98de29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('completed_on', sa.DateTime(), nullable=True))
    op.add_column('entries', sa.Column('deleted_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'deleted_on')
    op.drop_column('entries', 'completed_on')
    # ### end Alembic commands ###
