"""empty message

Revision ID: bfdff98de29d
Revises: e85ae82e159f
Create Date: 2017-12-24 13:45:01.409642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfdff98de29d'
down_revision = 'e85ae82e159f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('types', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'types', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'types', type_='foreignkey')
    op.drop_column('types', 'user_id')
    # ### end Alembic commands ###
