"""empty message

Revision ID: eae2507bae41
Revises: 98932c1ae504
Create Date: 2017-12-10 14:38:32.383398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae2507bae41'
down_revision = '98932c1ae504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('icloud_token', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'icloud_token')
    # ### end Alembic commands ###
