"""empty message

Revision ID: f8daafaad9b8
Revises: 5a0eba444019
Create Date: 2017-12-29 15:50:09.334025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8daafaad9b8'
down_revision = '5a0eba444019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'order')
    # ### end Alembic commands ###
